# Extra autostart processes
# exec-once = uwsm-app -- my-service
exec-once = sleep 1 && \
  if [[ "$(cat ~/.config/omarchy/current/theme/name 2>/dev/null)" == "zenities" ]]; then \
    pkill waybar; eww daemon && eww open bar; \
  fi

