# Learn how to configure Hyprland: https://wiki.hyprland.org/Configuring/
windowrule = opacity 0.7 0.7

windowrule = tag +term, match:class kitty

# Use defaults Omarchy defaults (but don't edit these directly!)
source = ~/.local/share/omarchy/default/hypr/autostart.conf
source = ~/.local/share/omarchy/default/hypr/bindings/media.conf
source = ~/.local/share/omarchy/default/hypr/bindings/clipboard.conf
source = ~/.local/share/omarchy/default/hypr/bindings/tiling-v2.conf
source = ~/.local/share/omarchy/default/hypr/bindings/utilities.conf
source = ~/.local/share/omarchy/default/hypr/envs.conf
source = ~/.local/share/omarchy/default/hypr/looknfeel.conf
source = ~/.local/share/omarchy/default/hypr/input.conf
source = ~/.local/share/omarchy/default/hypr/windows.conf
source = ~/.config/omarchy/current/theme/hyprland.conf

# Change your own setup in these files (and overwrite any settings from defaults!)
source = ~/.config/hypr/monitors.conf
source = ~/.config/hypr/input.conf
source = ~/.config/hypr/bindings.conf
source = ~/.config/hypr/envs.conf
source = ~/.config/hypr/looknfeel.conf
source = ~/.config/hypr/autostart.conf

# Add any other personal Hyprland configuration below
# windowrule = workspace 5, class:qemu

# NVIDIA environment variables
env = NVD_BACKEND,direct
env = LIBVA_DRIVER_NAME,nvidia
env = __GLX_VENDOR_LIBRARY_NAME,NVIDIA
# env = _JAVA_AWT_WM_NONREPARENTING,1
# env = AWT_TOOLKIT,XToolkit

# Reglas para solucionar problemas de foco/entrada en aplicaciones JetBrains (Toolbox, IDEA, etc.)

# 1. Asegura que las ventanas de JetBrains Toolbox tengan el foco inicial.
# windowrulev2 = focus, class:^(jetbrains-toolbox)$

# 2. Arregla los diálogos flotantes comunes (como los términos de servicio)
# y evita que pierdan el foco o sean transparentes al clic.
# Usa 'noinitialfocus' para evitar que Hyprland 'robe' el foco demasiado rápido.
# windowrulev2 = noinitialfocus, class:^("jetbrains-toolbox")$, title:^(".*(floating\_dialog|popup|dialog|terms|license|update).*")

# 3. Fuerza a que todas las ventanas de JetBrains usen el toolkit correcto (AWT_TOOLKIT ya es global, pero es redundante seguro)
# Añade esto en la sección 'exec' o 'env' de tu hyprland.conf (solo si no las habías añadido antes):
# env = AWT_TOOLKIT,XToolkit
# env = _JAVA_AWT_WM_NONREPARENTING,1
exec-once = hyprlock

# Glass effect for Waybar
layerrule = blur, waybar
layerrule = blurpopups, waybar
layerrule = ignorezero, waybar
